version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "limit-order-books-poloniex-6lambdas"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-b7t4hxqc4mrk"
s3_prefix = "limit-order-books-poloniex-6-lambdas"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "NotificationEmail=\"myemail\""

